openapi: 3.0.0
info:
  title: U1-M4-Summative-Alizada-Habib
  description:
    A simple service that allows get quote-of-the-day, word-of-the-day, and magic 8-ball.
  version: 0.0.1
servers:
  - url: 'http://localhost:8080'
    description: Local dev server
paths:

  /quote:  
    get:
      summary: Retrieves an entry for the quot of the day.
      responses:
        '200':
          description: Quot of the the day object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
          
  /word:
    get:
      summary: Retrieves an entry for the word of the day.
      responses:
        '200':
          description: Word of the day wity it's definition.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Definition'
                
  /magic:
    post:
      summary: Post a question
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Answer'
      responses:
        '201':
          description: Random answer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Answer'
        '400':
          description: Invalid request syntax.
        '422':
          description: Incomplete answer information. Some required fields missing.
      
    
          
    
components:
  schemas:
  
    Quote:
      properties:
        author:
          type: string
        quote:
          type: string
      required: 
        - author
        - quote
        
    Definition:
      properties:
        word:
          type: string
        definition:
          type: string
      required: 
        - word
        - definition
        
    Answer:
      properties:
        question:
          type: string
        answer:
          type: string
